"""
Vector model for the RAG system.
"""
from typing import Dict, Any, Optional, List
from .base import BaseModel


class Vector(BaseModel):
    """Numerical representation of chunk content generated by embedding model for similarity search."""

    def __init__(
        self,
        chunk_id: str,
        embedding: List[float],
        model_name: str = "text-embedding-v4",
        id: Optional[str] = None
    ):
        """Initialize vector.

        Args:
            chunk_id: Reference to parent chunk
            embedding: Numerical vector representation
            model_name: Name of embedding model used
            id: Optional unique identifier
        """
        super().__init__(id)
        self.chunk_id = chunk_id
        self.embedding = embedding
        self.model_name = model_name

    def to_dict(self) -> Dict[str, Any]:
        """Convert vector to dictionary representation.

        Returns:
            Dictionary representation of the vector
        """
        return {
            "id": self.id,
            "chunk_id": self.chunk_id,
            "embedding": self.embedding,
            "model_name": self.model_name,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat()
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Vector':
        """Create vector from dictionary representation.

        Args:
            data: Dictionary representation of the vector

        Returns:
            Vector instance
        """
        vector = cls(
            chunk_id=data["chunk_id"],
            embedding=data["embedding"],
            model_name=data.get("model_name", "text-embedding-v4"),
            id=data["id"]
        )

        vector.created_at = data.get("created_at") and datetime.fromisoformat(data["created_at"])
        vector.updated_at = data.get("updated_at") and datetime.fromisoformat(data["updated_at"])

        return vector

    def __str__(self) -> str:
        """String representation."""
        return f"Vector(chunk_id='{self.chunk_id}', model_name='{self.model_name}', dimensions={len(self.embedding)})"

    def __repr__(self) -> str:
        """Detailed string representation."""
        return f"Vector(id='{self.id}', chunk_id='{self.chunk_id}', model_name='{self.model_name}', dimensions={len(self.embedding)})"