openapi: 3.0.0
info:
  title: RAG Backend - Chat API
  description: API contract for conversational question answering functionality
  version: 1.0.0

paths:
  /chat:
    post:
      summary: Have a conversation about indexed documents
      description: Generate answers to questions based on indexed document content
      operationId: chatWithDocuments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - question
              properties:
                name:
                  type: string
                  description: Name/identifier for the document collection
                question:
                  type: string
                  description: The question to answer
                session_id:
                  type: string
                  description: Identifier for the chat session (for context)
                options:
                  type: object
                  properties:
                    top_k:
                      type: integer
                      description: Number of results to return
                      default: 5
                    enable_query_expansion:
                      type: boolean
                      description: Whether to expand the query
                      default: true
                    enable_reranking:
                      type: boolean
                      description: Whether to re-rank results
                      default: true
                    enable_vector_search:
                      type: boolean
                      description: Whether to perform vector search
                      default: true
                    enable_graph_search:
                      type: boolean
                      description: Whether to perform graph search
                      default: true
      responses:
        '200':
          description: Answer successfully generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The generated answer
                  sources:
                    type: array
                    items:
                      type: object
                      properties:
                        chunk_id:
                          type: string
                        document_title:
                          type: string
                        content:
                          type: string
                  session_id:
                    type: string
                    description: Identifier for the chat session
        '400':
          description: Invalid request parameters
        '404':
          description: Collection not found
        '500':
          description: Internal server error

components:
  schemas:
    ChatResponse:
      type: object
      properties:
        answer:
          type: string
        sources:
          type: array
          items:
            type: object
            properties:
              chunk_id:
                type: string
              document_title:
                type: string
              content:
                type: string
        session_id:
          type: string