openapi: 3.0.0
info:
  title: RAG Backend - Indexing API
  description: API contract for document indexing functionality
  version: 1.0.0

paths:
  /index:
    post:
      summary: Index a document
      description: Parse, chunk, and store a document for retrieval
      operationId: indexDocument
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - file_path
              properties:
                name:
                  type: string
                  description: Name/identifier for the document collection
                file_path:
                  type: string
                  description: Path to the PDF document to index
      responses:
        '200':
          description: Document successfully indexed
          content:
            application/json:
              schema:
                type: object
                properties:
                  document_id:
                    type: string
                    description: Unique identifier for the indexed document
                  status:
                    type: string
                    description: Status of the indexing operation
        '400':
          description: Invalid request parameters
        '404':
          description: File not found
        '500':
          description: Internal server error

components:
  schemas:
    IndexingResponse:
      type: object
      properties:
        document_id:
          type: string
        status:
          type: string